app/Http/routes.php
<?php

Route::get('/',[
  'uses' => 'productosController@index', 
  'as' => '/'
]);

Route::get('alta-genetics',[
  'uses' => 'productosController@alta', 
  'as' => 'AltaGenetics'
]);
Route::get('alta-genetics/{id}/{nombre}',[
  'uses' => 'productosController@seccion', 
  'as' => 'alta.seccion'
]);

Route::resource('mail','mailController');
	

Route::get('marketing-magic',[
  'uses' => 'productosController@marketing', 
  'as' => 'marketing-magic'
  ]);

Route::get('progenescatalogo',[
  'uses' => 'productosController@progenescatalogo', 
  'as' => 'progenescatalogo'
  ]);

Route::get('bmvcatalogo',[
  'uses' => 'productosController@bmvcatalogo', 
  'as' => 'bmvcatalogo'
  ]);

Route::get('celotor',[
  'uses' => 'productosController@celotor', 
  'as' => 'celotor'
  ]);
Route::get('detalles',[
  'uses' => 'productosController@detalles', 
  'as' => 'detalles'
  ]);

Route::get('producto/{id}/progenes',[
  'uses' => 'productosController@detallesProgenes', 
  'as' => 'detallesProgenes'
]);
Route::get('producto/{id}/altagenetics',[
  'uses' => 'productosController@detallesAlta', 
  'as' => 'detallesAlta'
]);
Route::get('producto/{id}/bmv',[
  'uses' => 'productosController@detallesBmv', 
  'as' => 'detallesBmv'
]);

Route::get('producto/{id}/listado',[
  'uses' => 'productosController@listado', 
  'as' => 'descuento.listado'
  ]);

Route::get('politicas-de-privacidad',[
  'uses' => 'productosController@politicas', 
  'as' => 'politicas'
  ]);

Route::get('terms',[
  'uses' => 'productosController@terminos', 
  'as' => 'terminos'
  ]);
Route::get('conocer-tu-marca',[
  'uses' => 'productosController@tumarca', 
  'as' => 'conocer-tu-marca'
  ]);
Route::get('reportar-problema',[
  'uses' => 'productosController@reportar', 
  'as' => 'reportar-problema'
  ]);
Route::get('buzon-de-sugenrecias',[
  'uses' => 'productosController@sugerencias', 
  'as' => 'buzon-de-sugenrecias'
  ]);
Route::get('asistencia-tecnica',[
  'uses' => 'productosController@asistencia', 
  'as' => 'asistencia-tecnica'
  ]);
Route::get('garantia-bmv-technology',[
  'uses' => 'productosController@garantia', 
  'as' => 'garantia-bmv-technology'
  ]);

Route::resource('activacion', 'activarController');
Route::resource('suscribir'	, 'suscribirController');
Route::resource('result'	, 'resultController');
Route::resource('log', 'logController');
Route::get('salir',[
  		'uses' => 'logController@logout',
  		'as'   => 'salir'
  	]);

Route::resource('registrar', 'userController');
Route::resource('contacto', 'contactoController');
Route::resource('success', 'successController');

Route::post('checking',[
      'uses' => 'codigotoroController@ver',
      'as'   => 'codigotoro.ver'
    ]);
Route::group(['prefix' => 'admin','middleware' => 'auth'], function(){
	
	Route::get('/',[
  		'uses' => 'adminController@index',
  		'as'   => '/'
  	]);
	Route::resource('inicio', 'adminController');
  	Route::resource('mensual', 'mensualController');
	Route::resource('carrusel', 'sliderController');
  Route::get('carrusel/destroy/{id}', [
    'uses' => 'sliderController@destroy',
    'as'  => 'admin.carrusel.destroy'
  ]);
   
   Route::resource('progenes', 'progenesController');
   Route::get('progenes/{id}/destroy',[
  		'uses' => 'progenesController@destroy',
  		'as'   => 'admin.progenes.destroy'
  	]);
    Route::resource('altagenetics', 'altageneticsController');
    Route::get('altagenetics/{id}/destroy',[
  		'uses' => 'altageneticsController@destroy',
  		'as'   => 'admin.altagenetics.destroy'
  	 ]);
   
    Route::resource('bmv', 'bmvController');
    Route::get('bmv/{id}/destroy',[
  		'uses' => 'bmvController@destroy',
  		'as'   => 'admin.bmv.destroy'
  	]);

    Route::resource('altacat', 'altacatController');
    Route::get('altacat/{id}/destroy',[
  		'uses' => 'altacatController@destroy',
  		'as'   => 'admin.altacat.destroy'
  	]);
   
    Route::resource('codigotoro', 'codigotoroController');
    Route::get('codigotoro/{id}/destroy',[
  		'uses' => 'codigotoroController@destroy',
  		'as'   => 'admin.codigotoro.destroy'
  	]);
    
   
    Route::resource('altasubcat', 'altasubcatController');
    Route::get('altasubcat/{id}/destroy',[
  		'uses' => 'altasubcatController@destroy',
  		'as'   => 'admin.altasubcat.destroy'
  	]);
   

	Route::resource('descuentos','descuentoController');
	Route::get('descuentos/{id}/destroy',[
  		'uses' => 'descuentoController@destroy',
  		'as'   => 'admin.descuentos.destroy'
  	]);
	Route::resource('suscriptor','suscriptorController');
	Route::get('suscriptor/{id}/destroy',[
  		'uses' => 'suscriptorController@destroy',
  		'as'   => 'admin.suscriptor.destroy'
  	]);
  	Route::get('semanal/{id}/add',[
      'uses' => 'semanalController@add',
      'as'   => 'admin.semanal.add'
    ]);
	Route::get('semanal/correo',[
      'uses' => 'semanalController@correo',
      'as'   => 'admin.semanal.correo'
    ]);
	
	
  	Route::get('mensual/{id}/add',[
      'uses' => 'mensualController@add',
      'as'   => 'admin.mensual.add'
    ]);
	Route::get('mensual/correo',[
      'uses' => 'mensualController@correo',
      'as'   => 'admin.mensual.correo'
    ]);
});

app/Altagenetics.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Altagenetics extends Model
{
    protected $table = 'altagenetics';
    protected $fillable = ['nombre','categoria','imagen','descripcion','precio','seccion','codigo','url'];
}

app/Http/Controllers/altageneticsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Session;
class altageneticsController extends Controller
{
      /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $product = \App\Altagenetics::orderBy('created_at','desc')->get();
       
        return view('admin.altagenetics.index', compact ('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         $cat = \App\Altacat::get();
         $subcat = \App\Altasubcat::get();
        return view('admin.altagenetics.create', compact('cat','subcat'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        $seccion = \App\Altacat::find($request->categoria); 
        $file = $request->file('imagen');
        $Imagen = 'image_'.time().'.'.$file->getClientOriginalExtension();
        $file->move(public_path().'/altagenetics', $Imagen);

        \App\Altagenetics::create([
            'nombre'            => $request['nombre'],
            'categoria'         => $request['categoria'],
            'imagen'            => $Imagen,
            'descripcion'       => $request['descripcion'],
            'codigo'            => $request['codigo'],
            'url'               => $request['url'],
            'seccion'           => $seccion->idcat
        ]);
		
        Session::flash('message','El producto se ha sido publicado correctamente');
        return redirect('admin/altagenetics');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = \App\Altagenetics::find($id);
        $cat = \App\Altacat::get();
         $subcat = \App\Altasubcat::get();
        return view ('admin.altagenetics.edit', compact('product','cat','subcat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $producto = \App\Altagenetics::find($id);
        if (!empty($request['imagen'])) {
            $file = $request->file('imagen');
            $Imagen = 'image_'.time().'.'.$file->getClientOriginalExtension();
            $file->move(public_path().'/altagenetics', $Imagen);

            
            $producto->fill([
                'nombre'            => $request['nombre'],
                'categoria'            => $request['categoria'],
                'imagen'            => $Imagen,
                'descripcion'       => $request['descripcion'],
                'precio'       => $request['precio'],
                'codigo'            => $request['codigo'],
                'url'               => $request['url'],
               
                  ])->save();
        }else{
            $producto->fill([
                  'nombre'            => $request['nombre'],
                  'categoria'            => $request['categoria'],
                  'descripcion'       => $request['descripcion'],
                  'precio'       => $request['precio'],
                  'codigo'            => $request['codigo'],
                  'url'               => $request['url'],
            ])->save();
        }
        
        Session::flash('message','El producto ha sido actualizado correctamente');
        return redirect('admin/altagenetics');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         \App\Altagenetics::destroy($id);
        Session::flash('destroy', 'El producto ha sido retirado exitosamente');
        return redirect('admin/altagenetics');
    }
}

resources/views/admin/altagenetics/create.blade.php
@extends('layouts.adminTemplate')

@section('contenido')
<br>
@if(count($errors)> 0)
<div class="ui inverted red segment">
  <ul>ERROR<hr>
  	 @foreach($errors->all() as $error)
  	 			
  	 			<li>{{$error}}</li>
  	 @endforeach
  </ul>
</div>
@endif

<div class="ui teal segments">
  <div class="ui inverted segment">
      <div class="ui segment" >
    {!!Form::open(['route'=>'admin.altagenetics.store','method'=>'POST', 'class'=>'ui form ingresar', 'files' => true, 'enctype'=>'multipart/form-data'])!!}
      <h2 class="ui dividing header">Información del producto</h2>
      <div class="fields">
        <div class="eight wide field">
          <label>Nombre</label>
          {!!Form::text('nombre', null,['placeholder'=>'Nombre del  producto...'])!!}
        </div>
        <div class="eight wide field">
          <label>Imagen</label>
            <div class="field">
              <input type="file" name="imagen">
          </div>
        </div>
         <div class="eight wide field">
         <label>Categoría</label>
          <select name="categoria">
             <option disabled>►Corte Zebu</option>
               @foreach($cat as $cats)
               @if($cats->idcat == 1)
               <option disabled>∟{{$cats->nombre}}</option>
                 @foreach($subcat as $subcats)
                   @if($subcats->idcat == $cats->id)
                     <option value="{{$subcats->id}}" >∟{{$subcats->nombre}}</option>
                   @endif
                 @endforeach
               @endif
               @endforeach
             <option disabled>►Corte Taurino</option>
              @foreach($cat as $cats)
                @if($cats->idcat == 2)
                 <option disabled>∟{{$cats->nombre}}</option>
               @foreach($subcat as $subcats)
                   @if($subcats->idcat == $cats->id)
                     <option value="{{$subcats->id}}"> ∟{{$subcats->nombre}}</option>
                   @endif
                 @endforeach
                @endif
              @endforeach
             <option disabled>►Leche Nacional</option>
              @foreach($cat as $cats)
               @if($cats->idcat == 3)
                  <option disabled>∟{{$cats->nombre}}</option>
               @foreach($subcat as $subcats)
                   @if($subcats->idcat == $cats->id)
                     <option value="{{$subcats->id}}"> ∟{{$subcats->nombre}}</option>
                   @endif
                 @endforeach
               @endif
              @endforeach
             <option disabled>►Leche Importada</option>
              @foreach($cat as $cats)
              @if($cats->idcat == 4)
                 <option disabled>∟{{$cats->nombre}}</option>
                @foreach($subcat as $subcats)
                   @if($subcats->idcat == $cats->id)
                     <option value="{{$subcats->id}}"> ∟{{$subcats->nombre}}</option>
                   @endif
                 @endforeach
                 @endif
               @endforeach
            </select>
        </div>
        <div class="eight wide field">
          <label>Codigo</label>
          {!!Form::text('codigo', null,['placeholder'=>'Codigo del toro'])!!}
        </div>
      </div>
      <div class="two fields">
        <div class="field">
          <label>Descripción</label>
          {!!Form::textarea('descripcion', null,['placeholder'=>'Descripción del descuento...', 'id'=>'descripcion'])!!}
        </div>
        
         <div class="eight wide field">
          <label>URL</label>
          {!!Form::text('url', null,['placeholder'=>'URL'])!!}
        </div>
      </div>
      
   
     
      <button class="ui primary submit button">Aceptar</button>
    {!!Form::open()!!}
  </div>
  </div>
</div>

@endsection

@section('js')
<script src="//cdn.ckeditor.com/4.6.0/standard/ckeditor.js"></script>
<script type="text/javascript">
CKEDITOR.replace("descripcion");
</script>
@endsection

resources/views/admin/altagenetics/edit.blade.php
@extends('layouts.adminTemplate')

@section('contenido')
<br>
@if(count($errors)> 0)
<div class="ui inverted red segment">
  <ul>ERROR<hr>
  	 @foreach($errors->all() as $error)
  	 			
  	 			<li>{{$error}}</li>
  	 @endforeach
  </ul>
</div>
@endif

<div class="ui teal segments">
  <div class="ui inverted segment">
      <div class="ui segment" >
    {!!Form::model($product, ['route'=>['admin.altagenetics.update', $product->id],'method'=>'PUT', 'class'=>'ui form ingresar', 'files' => true, 'enctype'=>'multipart/form-data'])!!}
      <h2 class="ui dividing header">Información del producto</h2>
      <div class="fields">
        <div class="eight wide field">
          <label>Nombre</label>
          {!!Form::text('nombre', null,['placeholder'=>'Nombre del  producto...'])!!}
        </div>
        <div class="eight wide field">
          <label>Imagen</label>
            <div class="field">
              <input type="file" name="imagen">
          </div>
        </div>
          <div class="eight wide field">
         <label>Categoría</label>
          <select name="categoria">
            <?php $cate = \App\Altasubcat::where('id', $product->categoria)->first(); ?>
            <option value="{{$product->categoria}}" >∟{!!$cate->nombre!!}</option>
             <option disabled>►Corte Zebu</option>
               @foreach($cat as $cats)
               @if($cats->idcat == 1)
               <option disabled>∟{{$cats->nombre}}</option>
                 @foreach($subcat as $subcats)
                   @if($subcats->idcat == $cats->id)
                     <option value="{{$subcats->id}}" >∟{{$subcats->nombre}}</option>
                   @endif
                 @endforeach
               @endif
               @endforeach
             <option disabled>►Corte Taurino</option>
              @foreach($cat as $cats)
                @if($cats->idcat == 2)
                 <option disabled>∟{{$cats->nombre}}</option>
               @foreach($subcat as $subcats)
                   @if($subcats->idcat == $cats->id)
                     <option value="{{$subcats->id}}"> ∟{{$subcats->nombre}}</option>
                   @endif
                 @endforeach
                @endif
              @endforeach
             <option disabled>►Leche Nacional</option>
              @foreach($cat as $cats)
               @if($cats->idcat == 3)
                  <option disabled>∟{{$cats->nombre}}</option>
               @foreach($subcat as $subcats)
                   @if($subcats->idcat == $cats->id)
                     <option value="{{$subcats->id}}"> ∟{{$subcats->nombre}}</option>
                   @endif
                 @endforeach
               @endif
              @endforeach
             <option disabled>►Leche Importada</option>
              @foreach($cat as $cats)
              @if($cats->idcat == 4)
                 <option disabled>∟{{$cats->nombre}}</option>
                @foreach($subcat as $subcats)
                   @if($subcats->idcat == $cats->id)
                     <option value="{{$subcats->id}}"> ∟{{$subcats->nombre}}</option>
                   @endif
                 @endforeach
                 @endif
               @endforeach
            </select>
        </div>
         <div class="eight wide field">
          <label>Codigo</label>
          {!!Form::text('codigo', null,['placeholder'=>'Codigo del toro'])!!}
        </div>
      </div>
       
         
      
      <div class="two fields">
        <div class="field">
          <label>Descripción</label>
          {!!Form::textarea('descripcion', null,['placeholder'=>'Descripción del descuento...', 'id'=>'descripcion'])!!}
        </div>
      </div>
         <div class="eight wide field">
          <label>URL</label>
          {!!Form::text('url', null,['placeholder'=>'URL'])!!}
        </div>
   
     
      <button class="ui primary submit button">Aceptar</button>
    {!!Form::open()!!}
  </div>
  </div>
</div>

@endsection

@section('js')
<script src="//cdn.ckeditor.com/4.6.0/standard/ckeditor.js"></script>
<script type="text/javascript">
CKEDITOR.replace("descripcion");
</script>
@endsection

resources/views/admin/altagenetics/index.blade.php
@extends('layouts.adminTemplate')

@section('contenido')

	@include('alerts.success')
	@include('alerts.destroy')

<div class="ui segment center aligned">
	<table class="ui compact inverted celled definition table">
  <thead class="full-width">
    <tr>
      <th>IMAGEN</th>
      <th>NOMBRE</th>
      <th>SUB CATEGORÍA</th>
      <th>CODIGO TORO</th>
      <th>OPCIÓN</th>
    </tr>
  </thead>
  <tbody>
  @foreach($product as $products)
   <?php $cate = \App\Altasubcat::where('id', $products->categoria)->first(); ?>
    <tr style="text-transform: uppercase;">
      <td class="collapsing">
          <img width="80px" src="{!!asset('altagenetics/'.$products->imagen)!!}" alt=""> <label></label>
      </td>
      <td>{!! $products->nombre!!}</td>
      <td>{!! $cate->nombre!!}</td>
      <td>{!! $products->codigo!!}</td>
      <td><a class="ui inverted button yellow icon floated" href="{!!asset('admin/altagenetics/'.$products->id.'/edit')!!}"><i class="ui icon edit"></i></a>
      	<a href="{{ route('admin.altagenetics.destroy',$products->id)}}" class="ui inverted button red icon floated"><i class="ui icon trash outline"></i></a> 
      	<a class="ui inverted button green icon floated" href=""><i class="ui icon unhide"></i></a>
      
      </td>
    </tr>
    @endforeach
  </tbody>
  <tfoot class="full-width">
    <tr>
      <th colspan="4">
      <a class="ui left floated large inverted blue button" href="{!!route('admin.altagenetics.create')!!}">Agregar producto</a>
      <a class="ui left floated large inverted blue button" href="{!!route('admin.altacat.index')!!}">Agregar categoría</a>
      <a class="ui left floated large inverted blue button" href="{!!route('admin.altasubcat.index')!!}">Agregar Subcategoría</a>
      </th>
      <th colspan="2">
          {!!Form::open(['route'=>'admin.descuentos.show', 'method'=>'get', 'class'=>'ui search left aligned'])!!}
			  <div class="ui icon input">
				{!!Form::hidden('resulset', null,['class'=>'prompt', 'placeholder'=>'Buscar producto'])!!}
				
			  </div>
			{!!Form::close()!!}
      </th>
    </tr>
  </tfoot>
</table>
</div>

@endsection