app/Http/routes.php
<?php

Route::get('/',[
  'uses' => 'productosController@index', 
  'as' => '/'
]);

Route::get('alta-genetics',[
  'uses' => 'productosController@alta', 
  'as' => 'AltaGenetics'
]);
Route::get('alta-genetics/{id}/{nombre}',[
  'uses' => 'productosController@seccion', 
  'as' => 'alta.seccion'
]);

Route::resource('mail','mailController');
	

Route::get('marketing-magic',[
  'uses' => 'productosController@marketing', 
  'as' => 'marketing-magic'
  ]);

Route::get('progenescatalogo',[
  'uses' => 'productosController@progenescatalogo', 
  'as' => 'progenescatalogo'
  ]);

Route::get('bmvcatalogo',[
  'uses' => 'productosController@bmvcatalogo', 
  'as' => 'bmvcatalogo'
  ]);

Route::get('celotor',[
  'uses' => 'productosController@celotor', 
  'as' => 'celotor'
  ]);
Route::get('detalles',[
  'uses' => 'productosController@detalles', 
  'as' => 'detalles'
  ]);

Route::get('producto/{id}/progenes',[
  'uses' => 'productosController@detallesProgenes', 
  'as' => 'detallesProgenes'
]);
Route::get('producto/{id}/altagenetics',[
  'uses' => 'productosController@detallesAlta', 
  'as' => 'detallesAlta'
]);
Route::get('producto/{id}/bmv',[
  'uses' => 'productosController@detallesBmv', 
  'as' => 'detallesBmv'
]);

Route::get('producto/{id}/listado',[
  'uses' => 'productosController@listado', 
  'as' => 'descuento.listado'
  ]);

Route::get('politicas-de-privacidad',[
  'uses' => 'productosController@politicas', 
  'as' => 'politicas'
  ]);

Route::get('terms',[
  'uses' => 'productosController@terminos', 
  'as' => 'terminos'
  ]);
Route::get('conocer-tu-marca',[
  'uses' => 'productosController@tumarca', 
  'as' => 'conocer-tu-marca'
  ]);
Route::get('reportar-problema',[
  'uses' => 'productosController@reportar', 
  'as' => 'reportar-problema'
  ]);
Route::get('buzon-de-sugenrecias',[
  'uses' => 'productosController@sugerencias', 
  'as' => 'buzon-de-sugenrecias'
  ]);
Route::get('asistencia-tecnica',[
  'uses' => 'productosController@asistencia', 
  'as' => 'asistencia-tecnica'
  ]);
Route::get('garantia-bmv-technology',[
  'uses' => 'productosController@garantia', 
  'as' => 'garantia-bmv-technology'
  ]);

Route::resource('activacion', 'activarController');
Route::resource('suscribir'	, 'suscribirController');
Route::resource('result'	, 'resultController');
Route::resource('log', 'logController');
Route::get('salir',[
  		'uses' => 'logController@logout',
  		'as'   => 'salir'
  	]);

Route::resource('registrar', 'userController');
Route::resource('contacto', 'contactoController');
Route::resource('success', 'successController');

Route::post('checking',[
      'uses' => 'codigotoroController@ver',
      'as'   => 'codigotoro.ver'
    ]);
Route::group(['prefix' => 'admin','middleware' => 'auth'], function(){
	
	Route::get('/',[
  		'uses' => 'adminController@index',
  		'as'   => '/'
  	]);
	Route::resource('inicio', 'adminController');
  	Route::resource('mensual', 'mensualController');
	Route::resource('carrusel', 'sliderController');
  Route::get('carrusel/destroy/{id}', [
    'uses' => 'sliderController@destroy',
    'as'  => 'admin.carrusel.destroy'
  ]);
   
   Route::resource('progenes', 'progenesController');
   Route::get('progenes/{id}/destroy',[
  		'uses' => 'progenesController@destroy',
  		'as'   => 'admin.progenes.destroy'
  	]);
    Route::resource('altagenetics', 'altageneticsController');
    Route::get('altagenetics/{id}/destroy',[
  		'uses' => 'altageneticsController@destroy',
  		'as'   => 'admin.altagenetics.destroy'
  	 ]);
   
    Route::resource('bmv', 'bmvController');
    Route::get('bmv/{id}/destroy',[
  		'uses' => 'bmvController@destroy',
  		'as'   => 'admin.bmv.destroy'
  	]);

    Route::resource('altacat', 'altacatController');
    Route::get('altacat/{id}/destroy',[
  		'uses' => 'altacatController@destroy',
  		'as'   => 'admin.altacat.destroy'
  	]);
   
    Route::resource('codigotoro', 'codigotoroController');
    Route::get('codigotoro/{id}/destroy',[
  		'uses' => 'codigotoroController@destroy',
  		'as'   => 'admin.codigotoro.destroy'
  	]);
    
   
    Route::resource('altasubcat', 'altasubcatController');
    Route::get('altasubcat/{id}/destroy',[
  		'uses' => 'altasubcatController@destroy',
  		'as'   => 'admin.altasubcat.destroy'
  	]);
   

	Route::resource('descuentos','descuentoController');
	Route::get('descuentos/{id}/destroy',[
  		'uses' => 'descuentoController@destroy',
  		'as'   => 'admin.descuentos.destroy'
  	]);
	Route::resource('suscriptor','suscriptorController');
	Route::get('suscriptor/{id}/destroy',[
  		'uses' => 'suscriptorController@destroy',
  		'as'   => 'admin.suscriptor.destroy'
  	]);
  	Route::get('semanal/{id}/add',[
      'uses' => 'semanalController@add',
      'as'   => 'admin.semanal.add'
    ]);
	Route::get('semanal/correo',[
      'uses' => 'semanalController@correo',
      'as'   => 'admin.semanal.correo'
    ]);
	
	
  	Route::get('mensual/{id}/add',[
      'uses' => 'mensualController@add',
      'as'   => 'admin.mensual.add'
    ]);
	Route::get('mensual/correo',[
      'uses' => 'mensualController@correo',
      'as'   => 'admin.mensual.correo'
    ]);
});

app/Descuento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Descuento extends Model
{
    protected $table = 'descuento';
    protected $fillable = ['nombre','imagen','descripcion','restriccion','empresa','telefono','direccion','ciudad','video','categoria','descuento','red_twitter','red_facebook','red_instagram','empresa_email','coordenadas','carnet_imagen','carnet_codigo','fecha_vencimiento'];

    public function setPathAttribute($imagen){
        $this->attribute[$imgen] = Carbon::now()->second.$imagen->getClientOriginalName();
        $name = Carbon::now()->second.$imagen->getClientOriginalName();
        \Storage::disk('local')->put($name, \File::get($imagen));
    }
}

app/Http/Controllers/descuentoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Mail;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use File;
use Session;
use App\Http\Requests\DescuentoRequest;

class descuentoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $descuento = \App\Descuento::orderBy('created_at', 'desc')->paginate(15);
        return view('admin.descuento.index', compact('descuento'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.descuento.publicar');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DescuentoRequest $request)
    {
        
        $file = $request->file('imagen');
        $Imagen = 'image_'.time().'.'.$file->getClientOriginalExtension();
        $file->move(public_path().'/descuentos', $Imagen);

        $file2 = $request->file('carnet_imagen');
        $Imagen2 = 'image_'.time().'.'.$file2->getClientOriginalExtension();
        $file2->move(public_path().'/carnet', $Imagen2);

        \App\Descuento::create([
            'nombre'            => $request['nombre'],
            'imagen'            => $Imagen,
            'descripcion'       => $request['descripcion'],
            'restriccion'       => $request['restriccion'],
            'empresa'           => $request['empresa'],
            'categoria'         => $request['categoria'],
            'ciudad'            => $request['ciudad'],
            'direccion'         => $request['direccion'],
            'descuento'         => $request['descuento'],
            'red_twitter'       => $request['red_twitter'],
            'red_facebook'      => $request['red_facebook'],
            'red_instagram'     => $request['red_instagram'],
            'empresa_email'     => $request['empresa_email'],
            'coordenadas'       => $request['coordenadas'],
            'carnet_imagen'     => $Imagen2,
            'carnet_codigo'     => $request['carnet_codigo'],
            'video'         => $request['video'],
            'fecha_vencimiento' => $request['fecha_vencimiento']

        ]);
		
		
		
        Session::flash('message','El descuento ha sido publicado correctamente');
        return redirect('admin/descuentos');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, Request $request)
    {
        $descuento = \App\Descuento::where('nombre', 'LIKE','%'.$request['resulset'].'%')->get();
		return view('admin.descuento.result', compact('descuento'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $descuento = \App\Descuento::find($id);
        return view('admin.descuento.editar', compact('descuento'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (!empty($request['imagen']) && empty($request['carnet_imagen'])) {
            $file = $request->file('imagen');
            $Imagen = 'image_'.time().'.'.$file->getClientOriginalExtension();
            $file->move(public_path().'/descuentos', $Imagen);

            $descuento = \App\Descuento::find($id);
            $descuento->fill([
                'nombre'            => $request['nombre'],
                'imagen'            => $Imagen,
                'descripcion'       => $request['descripcion'],
                'restriccion'       => $request['restriccion'],
                'empresa'           => $request['empresa'],
                'telefono'          => $request['telefono'],
                'ciudad'            => $request['ciudad'],
                'direccion'         => $request['direccion'],
                'categoria'         => $request['categoria'],
                'descuento'         => $request['descuento'],
                'red_twitter'       => $request['red_twitter'],
                'red_facebook'      => $request['red_facebook'],
                'red_instagram'     => $request['red_instagram'],
                'empresa_email'     => $request['empresa_email'],
                'coordenadas'       => $request['coordenadas'],
                'carnet_codigo'     => $request['carnet_codigo'],
                'video'         => $request['video'],
                'fecha_vencimiento' => $request['fecha_vencimiento']
            ])->save();
        }else if (empty($request['imagen']) && !empty($request['carnet_imagen'])) {
            $file2 = $request->file('carnet_imagen');
            $Imagen2 = 'image_'.time().'.'.$file2->getClientOriginalExtension();
            $file2->move(public_path().'/carnet', $Imagen2);

            $descuento = \App\Descuento::find($id);
            $descuento->fill([
                'nombre'            => $request['nombre'],
                'descripcion'       => $request['descripcion'],
                'restriccion'       => $request['restriccion'],
                'empresa'           => $request['empresa'],
                'telefono'          => $request['telefono'],
                'ciudad'            => $request['ciudad'],
                'direccion'         => $request['direccion'],
                'categoria'         => $request['categoria'],
                'descuento'         => $request['descuento'],
                'red_twitter'       => $request['red_twitter'],
                'red_facebook'      => $request['red_facebook'],
                'red_instagram'     => $request['red_instagram'],
                'empresa_email'     => $request['empresa_email'],
                'coordenadas'       => $request['coordenadas'],
                'carnet_imagen'     => $Imagen2,
                'carnet_codigo'     => $request['carnet_codigo'],
                'video'         => $request['video'],
                'fecha_vencimiento' => $request['fecha_vencimiento']
            ])->save();
        }else if (empty($request['imagen']) && empty($request['carnet_imagen'])) {
            $descuento = \App\Descuento::find($id);
            $descuento->fill($request->all())->save();
        }else if (!empty($request['imagen']) && !empty($request['carnet_imagen'])) {
            $file = $request->file('imagen');
            $Imagen = 'image_'.time().'.'.$file->getClientOriginalExtension();
            $file->move(public_path().'/descuentos', $Imagen);

            $file2 = $request->file('carnet_imagen');
            $Imagen2 = 'image_'.time().'.'.$file2->getClientOriginalExtension();
            $file2->move(public_path().'/carnet', $Imagen2);
            
            $descuento = \App\Descuento::find($id);
            $descuento->fill([
                'nombre'            => $request['nombre'],
                'imagen'            => $Imagen,
                'descripcion'       => $request['descripcion'],
                'restriccion'       => $request['restriccion'],
                'empresa'           => $request['empresa'],
                'telefono'          => $request['telefono'],
                'ciudad'            => $request['ciudad'],
                'direccion'         => $request['direccion'],
                'categoria'         => $request['categoria'],
                'descuento'         => $request['descuento'],
                'red_twitter'       => $request['red_twitter'],
                'red_facebook'      => $request['red_facebook'],
                'red_instagram'     => $request['red_instagram'],
                'empresa_email'     => $request['empresa_email'],
                'coordenadas'       => $request['coordenadas'],
                'carnet_imagen'     => $Imagen2,
                'carnet_codigo'     => $request['carnet_codigo'],
                'video'         	=> $request['video'],
                'fecha_vencimiento' => $request['fecha_vencimiento']
            ])->save();
        }

        
        Session::flash('message','El descuento ha sido actualizado correctamente');
        return redirect('admin/descuentos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\Descuento::destroy($id);
        Session::flash('destroy', 'El descuento ha sido retirado exitosamente');
        return redirect('admin/descuentos');
    }
}

resources/views/admin/descuento/editar.blade.php
@extends('layouts.adminTemplate')

@section('contenido')

<div class="ui teal segments">
  <div class="ui secondary segment">
    {!!Form::model($descuento, ['route'=>['admin.descuentos.update', $descuento->id],'method'=>'PUT', 'class'=>'ui form ingresar', 'files' => true, 'enctype'=>'multipart/form-data'])!!}
      <h2 class="ui dividing header">Información del descuento</h2>
      <div class="fields">
        <div class="eight wide field">
          <label>Nombre</label>
          {!!Form::text('nombre', null,['placeholder'=>'Nombre del descuento...'])!!}
        </div>
        <div class="eight wide field">
          <label>imagen</label>
            <div class="field">
              <input type="file" name="imagen">
          </div>
        </div>
      </div>
      <div class="two fields">
        <div class="field">
          <label>Descripción</label>
          {!!Form::textarea('descripcion', null,['placeholder'=>'Descripción del descuento...', 'id'=>'descripcion'])!!}
        </div>
        <div class="field">
          <label>Restricción</label>
            {!!Form::textarea('restriccion', null,['placeholder'=>'Restricción del descuento...', 'id'=>'restriccion'])!!}
        </div>
      </div>
       <div class="two fields">
        <div class="field">
          <label>Porcentaje de descuento</label>
          {!!Form::number('descuento', null,['placeholder'=>'50%'])!!}
        </div>
        <div class="field">
          <label>Fecha de vencimiento</label>
            {!!Form::date('fecha_vencimiento', \Carbon\Carbon::now())!!}
        </div>
      </div>
      <h2 class="ui dividing header">Información de la empresa</h2>
      <div class="field">
        <label>Descripción de la empresa</label>
          {!!Form::textarea('empresa', null,['id'=>'empresa'])!!}
      </div>
      <div class="fields">
        <div class="six wide field">
          <label> Facebook </label>
          {!!Form::text('red_facebook', null,['placeholder'=>'http://facebook.com/...'])!!}
        </div>
        <div class="six wide field">
          <label>Instagram</label>
          {!!Form::text('red_instagram', null,['placeholder'=>'http://instagram.com/...'])!!}
        </div>
        <div class="six wide field">
          <label>Twitter</label>
          {!!Form::text('red_twitter', null,['placeholder'=>'http://twitter.com/...'])!!}
        </div>
      </div>
      <div class="fields">
       <div class="six wide field">
          <label>Email</label>
          {!!Form::email('empresa_email', null,['placeholder'=>'correo@mail.co...'])!!}
        </div>
        <div class="three wide field">
          <label>Ciudad</label>
          {!!Form::text('ciudad', null,['placeholder'=>'Direccion'])!!}
        </div>
        <div class="three wide field">
          <label>Direccion</label>
          {!!Form::text('direccion', null,['placeholder'=>'Direccion'])!!}
        </div>
        <div class="six wide field">
          <label> telefono </label>
          {!!Form::text('telefono', null,['placeholder'=>'número telefonico'])!!}
        </div>
      </div>
      <div class="two fields">
        <div class="field eight wide">
          <label>Insertar vídeo</label>
          {!!Form::text('video', null,['placeholder'=>'http://superdescuentospanama.com...'])!!}
        </div>
      
        <div class="field eight wide">
          <label>Insertar mapa</label>
          {!!Form::text('coordenadas', null,['placeholder'=>'iframe src=https://www.google.com/...'])!!}
        </div>
      </div>
       <h2 class="ui dividing header">Carnet</h2>
        <div class="fields">
        <div class="eight wide field">
          <label>Codigo del carnet</label>
          {!!Form::text('carnet_codigo', null,['placeholder'=>'Nombre del descuento...'])!!}
        </div>
        <div class="eight wide field">
          <label>Imagen del carnet</label>
            <div class="field">
              {!!Form::file('carnet_imagen', null)!!}
          </div>
        </div>
      </div>
      <div class="fields">
        <div class="eight wide field">
          <label>Categoría</label>
          {!!Form::select('categoria', [
          '1' => 'Articulos Exclusivos',
          '2' => 'Belleza y Estetica',
          '3' => 'Entretenimiento',
          '4' => 'Hoteles y Turismo',
          '5' => 'Mascotas',
          '6' => 'Niños y Bebes',
          '7' => 'Restaurantes y Cafeterías',
          '8' => 'Salud',
          '9' => 'Servicios Automotrices',
          '10' => 'Servicios Corporativos',
          '11' => 'Tiendas'
          ])!!}
        </div>
      </div>
      <button class="ui primary submit button">Submit</button>
    {!!Form::open()!!}
  </div>
</div>

@endsection

@section('js')
<script src="//cdn.ckeditor.com/4.6.0/standard/ckeditor.js"></script>
<script type="text/javascript">
CKEDITOR.replace("descripcion");
CKEDITOR.replace("restriccion");
CKEDITOR.replace("empresa");
</script>
@endsection

resources/views/admin/descuento/index.blade.php
@extends('layouts.adminTemplate')

@section('contenido')

	@include('alerts.success')
	@include('alerts.destroy')

<div class="ui segment center aligned">
	<table class="ui compact inverted celled definition table">
  <thead class="full-width">
    <tr>
      <th></th>
      <th>TITULO</th>
      <th>DESC.</th>
      <th>CARNET</th>
      <th>OPCIÓN</th>
    </tr>
  </thead>
  <tbody>
  	@foreach($descuento as $Descuento)
    <tr style="text-transform: uppercase;">
      <td class="collapsing">
          <img width="64px" src="{!!asset('descuentos/'.$Descuento->imagen)!!}" alt=""> <label></label>
     
      </td>
      
      <td>{!!$Descuento->nombre!!}</td>
      <td><h2 class="ui header red">{!!$Descuento->descuento!!}%</h2></td>
      <td>{!!$Descuento->carnet_codigo!!}</td>
      <td><a class="ui inverted button yellow icon floated" href="{!!asset('admin/descuentos/'.$Descuento->id.'/edit')!!}"><i class="ui icon edit"></i></a>
      	<a href="{{ route('admin.descuentos.destroy',$Descuento->id)}}" class="ui inverted button red icon floated"><i class="ui icon trash outline"></i></a> 
      	<a class="ui inverted button green icon floated" href="{!!route('descuento.detalles', $Descuento->id)!!}"><i class="ui icon unhide"></i></a>
      	<a class="ui inverted button blue floated" href="{!!asset('admin/semanal/'.$Descuento->id.'/add')!!}">Descuento de la semana</a>
		<a class="ui inverted button green floated" href="{!!asset('admin/mensual/'.$Descuento->id.'/add')!!}">Descuento del mes</a>
      </td>
    </tr>
    @endforeach
  </tbody>
  <tfoot class="full-width">
    <tr>
      <th colspan="4">
      <a class="ui left floated large inverted blue button" href="{!!route('admin.descuentos.create')!!}">Agregar descuento</a>
      </th>
      <th colspan="2">
          {!!Form::open(['route'=>'admin.descuentos.show', 'method'=>'get', 'class'=>'ui search left aligned'])!!}
			  <div class="ui icon input">
				{!!Form::text('resulset', null,['class'=>'prompt', 'placeholder'=>'Buscar descuento'])!!}
				<i class="search icon"></i>
			  </div>
			{!!Form::close()!!}
      </th>
    </tr>
  </tfoot>
</table>
</div>

@endsection

resources/views/admin/descuento/publicar.blade.php
@extends('layouts.adminTemplate')

@section('contenido')
<br>
@if(count($errors)> 0)
<div class="ui inverted red segment">
  <ul>ERROR<hr>
  	 @foreach($errors->all() as $error)
  	 			
  	 			<li>{{$error}}</li>
  	 @endforeach
  </ul>
</div>
@endif

<div class="ui teal segments">
  <div class="ui inverted segment">
      <div class="ui segment" >
    {!!Form::open(['route'=>'admin.descuentos.store','method'=>'POST', 'class'=>'ui form ingresar', 'files' => true, 'enctype'=>'multipart/form-data'])!!}
      <h2 class="ui dividing header">Información del descuento</h2>
      <div class="fields">
        <div class="eight wide field">
          <label>Nombre</label>
          {!!Form::text('nombre', null,['placeholder'=>'Nombre del descuento...'])!!}
        </div>
        <div class="eight wide field">
          <label>imagen</label>
            <div class="field">
              <input type="file" name="imagen">
          </div>
        </div>
      </div>
      <div class="two fields">
        <div class="field">
          <label>Descripción</label>
          {!!Form::textarea('descripcion', null,['placeholder'=>'Descripción del descuento...', 'id'=>'descripcion'])!!}
        </div>
        <div class="field">
          <label>Restricción</label>
            {!!Form::textarea('restriccion', null,['placeholder'=>'Restricción del descuento...', 'id'=>'restriccion'])!!}
        </div>
      </div>
       <div class="two fields">
        <div class="field">
          <label>Porcentaje de descuento</label>
          {!!Form::number('descuento', null,['placeholder'=>'50%'])!!}
        </div>
        <div class="field">
          <label>Fecha de vencimiento</label>
            {!!Form::date('fecha_vencimiento', \Carbon\Carbon::now())!!}
        </div>
      </div>
      <h2 class="ui dividing header">Información de la empresa</h2>
      <div class="field">
        <label>Descripción de la empresa</label>
          {!!Form::textarea('empresa', null,['id'=>'empresa'])!!}
      </div>
      <div class="fields">
        <div class="six wide field">
          <label> Facebook </label>
          {!!Form::text('red_facebook', null,['placeholder'=>'http://facebook.com/...'])!!}
        </div>
        <div class="six wide field">
          <label>Instagram</label>
          {!!Form::text('red_instagram', null,['placeholder'=>'http://instagram.com/...'])!!}
        </div>
        <div class="six wide field">
          <label>Twitter</label>
          {!!Form::text('red_twitter', null,['placeholder'=>'http://twitter.com/...'])!!}
        </div>
      </div>
      <div class="fields">
       <div class="six wide field">
          <label>Email</label>
          {!!Form::email('empresa_email', null,['placeholder'=>'correo@mail.co...'])!!}
        </div>
        <div class="three wide field">
          <label>Ciudad</label>
          {!!Form::text('ciudad', null,['placeholder'=>'Direccion'])!!}
        </div>
        <div class="three wide field">
          <label>Direccion</label>
          {!!Form::text('direccion', null,['placeholder'=>'Direccion'])!!}
        </div>
        <div class="six wide field">
          <label> telefono </label>
          {!!Form::text('telefono', null,['placeholder'=>'número telefonico'])!!}
        </div>
      </div>
      <div class="two fields">
        <div class="field eight wide">
          <label>Insertar vídeo</label>
          {!!Form::text('video', null,['placeholder'=>'http://superdescuentospanama.com...'])!!}
        </div>
      
        <div class="field eight wide">
          <label>Insertar mapa</label>
          {!!Form::text('coordenadas', null,['placeholder'=>'iframe src=https://www.google.com/...'])!!}
        </div>
      </div>
       <h2 class="ui dividing header">Carnet</h2>
        <div class="fields">
        <div class="eight wide field">
          <label>Codigo del carnet</label>
          {!!Form::text('carnet_codigo', null,['placeholder'=>'Nombre del descuento...'])!!}
        </div>
        <div class="eight wide field">
          <label>Imagen del carnet</label>
            <div class="field">
              {!!Form::file('carnet_imagen', null)!!}
          </div>
        </div>
      </div>
      <div class="fields">
        <div class="eight wide field">
          <label>Categoría</label>
          {!!Form::select('categoria', [
          '1' => 'Articulos Exclusivos',
          '2' => 'Belleza y Estetica',
          '3' => 'Entretenimiento',
          '4' => 'Hoteles y Turismo',
          '5' => 'Mascotas',
          '6' => 'Niños y Bebes',
          '7' => 'Restaurantes y Cafeterías',
          '8' => 'Salud',
          '9' => 'Servicios Automotrices',
          '10' => 'Servicios Corporativos',
          '11' => 'Tiendas'
          ])!!}
        </div>
      </div>
      <button class="ui primary submit button">Aceptar</button>
    {!!Form::open()!!}
  </div>
  </div>
</div>

@endsection

@section('js')
<script src="//cdn.ckeditor.com/4.6.0/standard/ckeditor.js"></script>
<script type="text/javascript">
CKEDITOR.replace("descripcion");
CKEDITOR.replace("restriccion");
CKEDITOR.replace("empresa");
</script>
@endsection

resources/views/admin/descuento/result.blade.php
@extends('layouts.adminTemplate')

@section('contenido')

	@include('alerts.success')
	@include('alerts.destroy')

<div class="ui segment center aligned">
	<table class="ui compact inverted celled definition table">
  <thead class="full-width">
    <tr>
      <th></th>
      <th>TITULO</th>
      <th>DESC.</th>
      <th>CARNET</th>
      <th>URL</th>
      <th>OPCIÓN</th>
    </tr>
  </thead>
  <tbody>
  	@foreach($descuento as $Descuento)
    <tr style="text-transform: uppercase;">
      <td class="collapsing">
          <img width="64px" src="{!!asset('descuentos/'.$Descuento->imagen)!!}" alt=""> <label></label>
     
      </td>
      
      <td>{!!$Descuento->nombre!!}</td>
      <td><h2 class="ui header red">{!!$Descuento->descuento!!}%</h2></td>
      <td>{!!$Descuento->carnet_codigo!!}</td>
      <td>{!!$Descuento->sitio_url!!}</td>
      <td><a class="ui inverted button yellow icon floated" href="{!!asset('admin/descuentos/'.$Descuento->id.'/edit')!!}"><i class="ui icon edit"></i></a>
      <a href="{{ route('admin.descuentos.destroy',$Descuento->id)}}" class="ui inverted button red icon floated"><i class="ui icon trash outline"></i></a> 
      <a class="ui inverted button green icon floated" href="{!!route('descuento.detalles', $Descuento->id)!!}"><i class="ui icon unhide"></i></a>
      	<a class="ui inverted button blue floated" href="{!!asset('admin/semanal/'.$Descuento->id.'/add')!!}">Descuento de la semana</a>
		<a class="ui inverted button green floated" href="{!!asset('admin/mensual/'.$Descuento->id.'/add')!!}">Descuento del mes</a>
      </td>
    </tr>
    @endforeach
  </tbody>
  <tfoot class="full-width">
    <tr>
      <th colspan="5">
      <a class="ui left floated large inverted blue button" href="{!!route('admin.descuentos.create')!!}">Agregar descuento</a>
      </th>
      <th colspan="2">
          {!!Form::open(['route'=>'admin.descuentos.show', 'method'=>'get', 'class'=>'ui search left floated'])!!}
			  <div class="ui icon input">
				{!!Form::text('resulset', null,['class'=>'prompt left floated', 'placeholder'=>'Buscar descuento'])!!}
				<i class="search icon"></i>
			  </div>
			{!!Form::close()!!}
      </th>
    </tr>
  </tfoot>
</table>
</div>

@endsection